import { StyleSheet } from 'react-native';
import {
  FONT_DISPLAY,
  FONT_BODY,
  FONT_MONO,
  COLOR_BG_BASE,
  COLOR_BG_CARD,
  COLOR_BORDER,
  COLOR_GOLD,
  COLOR_TIJOLO,
} from '../../lib/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLOR_BG_BASE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1.5,
    borderBottomColor: COLOR_BORDER,
    backgroundColor: COLOR_BG_BASE,
  },
  headerBack: {
    paddingVertical: 6,
  },
  headerBackText: {
    color: '#a1a1aa',
    fontSize: 14,
    fontWeight: '500',
    fontFamily: FONT_BODY,
  },
  stepIndicator: {
    color: COLOR_GOLD,
    fontSize: 12,
    fontWeight: '600',
    fontFamily: FONT_BODY,
  },
  body: {
    flex: 1,
    padding: 24,
  },
  stepContainer: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 0.5,
    fontFamily: FONT_DISPLAY,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: '#a1a1aa',
    fontWeight: '400',
    marginTop: 4,
    marginBottom: 24,
    fontFamily: FONT_BODY,
  },
  listContent: {
    paddingBottom: 24,
  },
  serviceCard: {
    backgroundColor: COLOR_BG_CARD,
    borderWidth: 1.5,
    borderRightWidth: 4.5,
    borderBottomWidth: 4.5,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    padding: 16,
    marginBottom: 12,
    gap: 8,
  },
  selectedCard: {
    borderColor: COLOR_GOLD,
    backgroundColor: 'rgba(212, 175, 55, 0.03)',
  },
  serviceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  serviceName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    flex: 1,
    marginRight: 12,
    fontFamily: FONT_DISPLAY,
  },
  servicePrice: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLOR_GOLD,
    fontFamily: FONT_MONO,
  },
  serviceDesc: {
    fontSize: 12,
    color: '#a1a1aa',
    lineHeight: 18,
    fontWeight: '400',
    fontFamily: FONT_BODY,
  },
  serviceFooter: {
    flexDirection: 'row',
    marginTop: 4,
  },
  serviceDuration: {
    fontSize: 11,
    color: COLOR_GOLD,
    fontWeight: '500',
    fontFamily: FONT_BODY,
  },
  barberCard: {
    backgroundColor: COLOR_BG_CARD,
    borderWidth: 1.5,
    borderRightWidth: 4.5,
    borderBottomWidth: 4.5,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    padding: 16,
    marginBottom: 12,
  },
  barberInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  barberAvatarBadge: {
    width: 48,
    height: 48,
    borderRadius: 4,
    borderWidth: 1.5,
    borderRightWidth: 2.5,
    borderBottomWidth: 2.5,
    borderColor: COLOR_BORDER,
    backgroundColor: COLOR_BG_BASE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  barberInitials: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLOR_GOLD,
    fontFamily: FONT_DISPLAY,
  },
  barberAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 4,
  },
  barberTextContent: {
    flex: 1,
    gap: 4,
  },
  barberName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    fontFamily: FONT_DISPLAY,
  },
  barberBio: {
    fontSize: 12,
    color: '#a1a1aa',
    fontWeight: '400',
    lineHeight: 16,
    fontFamily: FONT_BODY,
  },
  emptyText: {
    fontSize: 13,
    color: '#71717a',
    textAlign: 'center',
    marginTop: 40,
    fontWeight: '400',
    fontFamily: FONT_BODY,
  },
  nextBtn: {
    height: 48,
    backgroundColor: COLOR_GOLD,
    borderRadius: 4,
    borderWidth: 1.5,
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderColor: COLOR_BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  nextBtnText: {
    color: '#0f0e0d',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 1.5,
    fontFamily: FONT_BODY,
  },
  stepFooterBtns: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  backBtn: {
    height: 48,
    borderWidth: 1.5,
    borderRightWidth: 3.5,
    borderBottomWidth: 3.5,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    backgroundColor: COLOR_BG_CARD,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  backBtnText: {
    color: '#a1a1aa',
    fontSize: 13,
    fontWeight: '600',
    fontFamily: FONT_BODY,
  },
  dateSelectorContainer: {
    height: 80,
    marginBottom: 20,
  },
  dateScroll: {
    gap: 10,
    paddingRight: 24,
  },
  dateBtn: {
    width: 60,
    height: 72,
    borderWidth: 1.5,
    borderRightWidth: 3.5,
    borderBottomWidth: 3.5,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    backgroundColor: COLOR_BG_CARD,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  dateBtnSelected: {
    borderColor: COLOR_GOLD,
    backgroundColor: 'rgba(212, 175, 55, 0.05)',
  },
  dateDayName: {
    fontSize: 9,
    color: '#71717a',
    fontWeight: '500',
    fontFamily: FONT_BODY,
  },
  dateDayNum: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    fontFamily: FONT_DISPLAY,
  },
  dateMonthName: {
    fontSize: 9,
    color: '#71717a',
    fontWeight: '500',
    fontFamily: FONT_BODY,
  },
  dateTextSelected: {
    color: COLOR_GOLD,
  },
  slotsContainer: {
    flex: 1,
  },
  selectDatePrompt: {
    fontSize: 13,
    color: '#71717a',
    textAlign: 'center',
    marginTop: 40,
    fontWeight: '400',
    fontFamily: FONT_BODY,
  },
  slotRow: {
    justifyContent: 'flex-start',
    gap: 10,
    marginBottom: 10,
  },
  slotBtn: {
    flex: 1,
    maxWidth: '23%',
    height: 38,
    borderWidth: 1.5,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    backgroundColor: COLOR_BG_CARD,
    alignItems: 'center',
    justifyContent: 'center',
  },
  slotBtnSelected: {
    borderColor: COLOR_GOLD,
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
  },
  slotText: {
    fontSize: 13,
    color: '#ffffff',
    fontFamily: FONT_MONO,
  },
  slotTextSelected: {
    color: COLOR_GOLD,
    fontWeight: '600',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(15, 14, 13, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  errorBanner: {
    backgroundColor: 'rgba(127, 29, 29, 0.1)',
    borderColor: COLOR_TIJOLO,
    borderWidth: 1.5,
    borderRightWidth: 3.5,
    borderBottomWidth: 3.5,
    padding: 12,
    borderRadius: 4,
    marginBottom: 16,
    marginHorizontal: 24,
  },
  errorText: {
    color: '#f87171',
    fontSize: 12,
    fontFamily: FONT_BODY,
  },
  successContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  successBadge: {
    width: 80,
    height: 80,
    borderRadius: 4,
    backgroundColor: 'rgba(20, 83, 45, 0.1)',
    borderWidth: 1.5,
    borderRightWidth: 3.5,
    borderBottomWidth: 3.5,
    borderColor: 'rgba(21, 128, 61, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  successEmoji: {
    fontSize: 36,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    fontFamily: FONT_DISPLAY,
  },
  successDesc: {
    fontSize: 13,
    color: '#a1a1aa',
    textAlign: 'center',
    fontWeight: '400',
    lineHeight: 18,
    marginTop: 8,
    marginBottom: 28,
    paddingHorizontal: 16,
    fontFamily: FONT_BODY,
  },
  receipt: {
    width: '100%',
    backgroundColor: COLOR_BG_CARD,
    borderWidth: 1.5,
    borderRightWidth: 4.5,
    borderBottomWidth: 4.5,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    padding: 20,
    gap: 12,
    marginBottom: 32,
  },
  receiptRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  receiptLabel: {
    fontSize: 12,
    color: '#a1a1aa',
    fontFamily: FONT_BODY,
  },
  receiptValue: {
    fontSize: 13,
    color: '#ffffff',
    fontWeight: '500',
    fontFamily: FONT_BODY,
  },
  guestForm: {
    gap: 16,
    marginBottom: 24,
    backgroundColor: COLOR_BG_CARD,
    borderWidth: 1.5,
    borderRightWidth: 4.5,
    borderBottomWidth: 4.5,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    padding: 20,
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    color: '#a1a1aa',
    fontWeight: '500',
    fontFamily: FONT_BODY,
  },
  textInput: {
    height: 48,
    backgroundColor: COLOR_BG_BASE,
    borderWidth: 1.5,
    borderColor: COLOR_BORDER,
    borderRadius: 4,
    paddingHorizontal: 16,
    color: '#f3f4f6',
    fontSize: 14,
    fontFamily: FONT_BODY,
  },
});
